DECLARE
   objExists   CHAR (1);
BEGIN
   BEGIN
      SELECT 'Y'
        INTO objExists
        FROM tab
       WHERE tname = 'FT_E_CGP1';
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         objExists := 'N';
   END;

   IF objExists = 'N'
   THEN
      EXECUTE IMMEDIATE
         ('CREATE TABLE FT_E_CGP1
		(
		CGP1_OID    CHAR(10 BYTE)    NOT NULL,
		CGR1_OID    CHAR(10 BYTE)    NOT NULL,
		CAL_ID    VARCHAR2(10 BYTE),    
		LAST_CHG_TMS    DATE    NOT NULL,
		LAST_CHG_USR_ID    VARCHAR2(256 BYTE)    NOT NULL,
		START_TMS    DATE    NOT NULL,
		END_TMS    DATE,
		PRT_PURP_TYP    VARCHAR2(8 BYTE)    NOT NULL,
		PART_TYP    CHAR(8 BYTE),    
		PRT_DESC    VARCHAR2(254 BYTE),    
		PART_CURR_CDE    CHAR(3 BYTE),  
		PART_CAMT    NUMBER(31,11),    
		PART_CPCT    NUMBER(18,12),    
		DATA_STAT_TYP    VARCHAR2(20 BYTE),    
		DATA_SRC_ID    VARCHAR2(40 BYTE)
		)');

      EXECUTE IMMEDIATE
         ('CREATE UNIQUE INDEX FT_E_CGP1_PK ON FT_E_CGP1 (CGP1_OID)');
		 
	  EXECUTE IMMEDIATE
         ('CREATE INDEX FT_X_CGP1_I002 ON FT_E_CGP1 (CAL_ID)');
		 
	  EXECUTE IMMEDIATE
         ('CREATE UNIQUE INDEX FT_X_CGP1_U001 ON FT_E_CGP1 (CGR1_OID, PRT_PURP_TYP, CAL_ID, START_TMS)');

      EXECUTE IMMEDIATE
         ('ALTER TABLE FT_E_CGP1 ADD CONSTRAINT FT_E_CGP1_PK PRIMARY KEY (CGP1_OID)');
		 
	  EXECUTE IMMEDIATE
         ('ALTER TABLE FT_E_CGP1 ADD(CONSTRAINT CGP1F001 FOREIGN KEY (CGR1_OID) REFERENCES FT_E_CGR1 (CGR1_OID))');
		 
	  EXECUTE IMMEDIATE
         ('ALTER TABLE FT_E_CGP1 ADD CONSTRAINT CGP1F002 FOREIGN KEY (CAL_ID) REFERENCES FT_T_CADF(CAL_ID)');

      EXECUTE IMMEDIATE ('CREATE OR REPLACE SYNONYM FT_T_CGP1 FOR FT_E_CGP1');
   ELSE
      DBMS_OUTPUT.put_line ('Table FT_E_CGP1 already exists');
   END IF;
END;
/